name: TP
services:
  postgresql:
    image: postgres:17
    environment:
      - POSTGRES_USER=test
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
